apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployafter
  labels:
    app: javaspringmaven
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javaspringmaven
  template:
    metadata:
      labels:
        app: javaspringmaven
    spec:
      containers:
      - name: jekspringwebapp
        image: jchoo/jekspringwebappmavennoagent:v2
        ports:
        - containerPort: 8080