---
apiVersion: v1
kind: Pod
metadata:
  name: counter
  labels:
    app: counter
    version: v1.0
spec:
  containers:
  - name: count
    image: busybox
    args: [/bin/sh, -c,
            'while true; do number=""; while [ ${#number} -lt 10 ]; do number="${number}$RANDOM"; done; echo "Random 10-digit number: ${number:0:10}"; sleep 2; done']
