version: '3'
services:
    # juiceshop: 
    #     image: bkimminich/juice-shop
    #     expose:
    #      - "3000"
    nginx: 
        image: nginx 
        volumes:
        - ./conf.d:/etc/nginx/conf.d
        - ./ssl:/etc/nginx/ssl
        ports:
            - "80:80"
            - "443:443"